apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: new-app
spec:
  containers:
    - name: nginx
      image: 'nginx:1.14.2'
      resources:
        requests:
          memory: "128M"
          cpu: "0.2"
        limits:
          memory: "256M"
          cpu: "0.5"
      ports:
        - containerPort: 80