apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: requarks/wiki:latest
          ports:
            - containerPort: 3000
          env:
            - name: "DB_TYPE"
              value: "postgres"
            - name: "DB_HOST"
              value: "wikijs-postgresql"
            - name: "DB_PORT"
              value: "5432"
            - name: "DB_NAME"
              value: "wikidb"
            - name: "DB_USER"
              value: "wikiuser"
            - name: "DB_PASS"
              valueFrom:
                secretKeyRef:
                  name: wikijs-postgresql
                  key: postgresql-password
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"