apiVersion: v1
kind: Service
metadata:
  name: wikijs
  namespace: wiki
spec:
  type: LoadBalancer  # Use NodePort if you are running a local cluster
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: wikijs